* Definition
* Features
* Ndarray
* Operation in Numpy:
* Dictionary

## What is Numpy?

Numpy is a powerful library for numeric and scientific computing in python

Feature of Numpy

- Faster than lists(Because it uses contigous memory allocation)
- Supports mutideminsion arrays (Ndarrays).
- Otimized for mathematical and statistical operations.
- Used in many fields like Data Science, Machine Learning and almost all domains from Finance to insurance.

In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 5.8 MB/s eta 0:00:00a 0:00:01m


In [4]:
import numpy as np

import time
lst = list(range(100000))
arr = np.arange(100000)

start = time.time()
sum(lst)
print("list time:",time.time() - start)

start = time.time()
np.sum(arr)
print("numpy time:",time.time() - start)

list time: 0.0004134178161621094
numpy time: 0.0002498626708984375


## Ndarray - The heart of Numpy

An Ndarray (N-dimensional array) is the fundamental data structure in Numpy

it is homogeneous collection of data stored in a grid format

### Creat Array

In [5]:
# 1D array
arr1 = np.array([1,2,3,4])
print("1D array",arr1)

1D array [1 2 3 4]


In [7]:
# 2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr2)

2D array:
 [[1 2 3]
 [4 5 6]]


In [8]:
#Array if zeros, one, range
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Array if zeros, one, range
one = np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Range array
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


## Array operation

In [17]:
arr_a = np.array([1,2,3])
arr_b = np.array([10,20,30])

print("Addtion of Array",arr_a + arr_b)
print("Multiplication of Array",arr_a * arr_b)
print("Division of Array",arr_b / 2)
print("squared of Array",arr_a ** 2)

Addtion of Array [11 22 33]
Multiplication of Array [10 40 90]
Division of Array [ 5. 10. 15.]
squared of Array [1 4 9]


In [19]:
# Broad castng
matrix = np.array([[1,2],[3,4]])
print("original matrix\n",matrix)
print()
print("Add scalar 5:\n",matrix + 5)

original matrix
 [[1 2]
 [3 4]]

Add scalar 5:
 [[6 7]
 [8 9]]


## Indexing, slicing Reshaping

In [22]:
arr = np.array([[10,20,30],[40,50,60]])
print("original array:\n",arr)
print()

# indexing
print("Element [0,1]",arr[0,1])

original array:
 [[10 20 30]
 [40 50 60]]

Element [0,1] 20


In [24]:
#slicing
print("First row",arr[1:])

First row [[40 50 60]]


In [27]:
print("First row",arr[:,-1])

First row [30 60]


In [26]:
print(arr)

[[10 20 30]
 [40 50 60]]


In [30]:
# Reshaping
reshape = np.arange(12).reshape(3,4)
print(reshape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
## Useful funtion of Numpy
arr = np.array([4,7,2,8,3])
print("Mean:",np.mean(arr))

Mean: 4.8


In [32]:
print("Standard Deviation:",np.std(arr))

Mean: 2.3151673805580453


In [33]:
print("Standard Deviation:",np.sort(arr))

Standard Deviation: [2 3 4 7 8]


In [36]:
#linespace
lin = np.linspace(0,1,5)
print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [38]:
# Random
rand = np.random.randint(1,10,(2,3))
print(rand)

[[1 8 3]
 [3 8 3]]


## Quiz

In [40]:
# can you create matrix with values from 1 to 25

In [55]:
matrixQz = np.arange(1,26).reshape(5,5)
print(matrixQz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
# get the middle matrix of dimesion 3 X 3
matrixQz = matrixQz[1:4,1:4]
print(matrixQz)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [62]:
# sum of each row
row_sum = np.sum(matrixQz,axis=1)
print("Row wise sum",row_sum)

Row wise sum [24 39 54]


In [64]:
# sum of each column
column_sum = np.sum(matrixQz,axis=0)
print("column wise sum",column_sum)

column wise sum [36 39 42]
